apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-12T16:15:32Z"
    generateName: final-exam-7467cb7888-
    labels:
      app: final-exam
      pod-template-hash: 7467cb7888
    name: final-exam-7467cb7888-4fwp4
    namespace: ibrohim-final
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: final-exam-7467cb7888
      uid: cd4f6b4a-8b9d-43a5-ae57-28d6e8132dc7
    resourceVersion: "21331158"
    uid: 8a21682e-c899-4f4f-920e-8a7b6843feed
  spec:
    containers:
    - env:
      - name: AUTHOR
        value: IBROHIM
      - name: POD
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: NODE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      image: nvrbckdown/flask-app:last-practice
      imagePullPolicy: IfNotPresent
      name: flask-app
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-f9rnd
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: node2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-f9rnd
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-04-12T16:15:33Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-12T16:15:32Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-04-12T16:15:33Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-04-12T16:15:33Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-12T16:15:32Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://824547c39b146da141fc61d4b7c0fcaad6bc0eeee856d8d7874005927a3ea33c
      image: docker.io/nvrbckdown/flask-app:last-practice
      imageID: docker.io/nvrbckdown/flask-app@sha256:ea3b5d9da60442d4d12a2fc0c02d993e836acc8df83e0b18035745a2eddc5510
      lastState: {}
      name: flask-app
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-04-12T16:15:33Z"
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-f9rnd
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 65.108.62.223
    hostIPs:
    - ip: 65.108.62.223
    phase: Running
    podIP: 10.233.66.232
    podIPs:
    - ip: 10.233.66.232
    qosClass: BestEffort
    startTime: "2025-04-12T16:15:32Z"
kind: List
metadata:
  resourceVersion: ""
