apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-exam
  template:
    metadata:
      labels:
        app: final-exam
    spec:
      containers:
      - name: flask-app
        image: nvrbckdown/flask-app:last-practice
        env:
        - name: AUTHOR
          value: "IBROHIM"
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

