apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-12T16:07:25Z"
  labels:
    author: IBROHIM
    last: final
  name: nginx1
  namespace: ibrohim-final
  resourceVersion: "21323414"
  uid: 13dcd632-d7c4-4928-9206-00abfe6f3242
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9nvvg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-9nvvg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-12T16:07:29Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-12T16:07:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-12T16:07:29Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-12T16:07:29Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-12T16:07:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e5467eb8fdb1135639880b7a358e0ce737be198477238ac42a496823d48f980a
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:09369da6b10306312cd908661320086bf87fbae1b6b0c49a1f50ba531fef2eab
    lastState: {}
    name: nginx1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-04-12T16:07:28Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9nvvg
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 65.108.62.223
  hostIPs:
  - ip: 65.108.62.223
  phase: Running
  podIP: 10.233.66.67
  podIPs:
  - ip: 10.233.66.67
  qosClass: BestEffort
  startTime: "2025-04-12T16:07:25Z"
