apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  template:
    metadata:
      labels:
        app: frontend-something
    spec:
      containers:
      - name: frontend-something
        image: nvrbckdownsomething
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/hostname: node2

