apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJNeV9sb2dpbiIsInBhc3N3b3JkIjoiTXktcGFzc3dvcmQiLCJlbWFpbCI6InByb3hpbWFfdWFjYWRlbXlAZ21haWwuY29tIiwiYXV0aCI6IlRYbGZiRzluYVc0NlRYa3RjR0Z6YzNkdmNtUT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
