apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-configmap
  template:
    metadata:
      labels:
        app: nginx-configmap
    spec:
      containers:
      - name: nginx
        image: nginx
        command: [ "sh", "-c" ]
        args:
          - |
            echo "My name is $AUTHOR and this is my exam";
            sleep 3600
        env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: AUTHOR
        - name: EXAM_TYPE
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: EXAM_TYPE

